### ISSUE TITLE
travis CI build sticker

### ISSUE THREAD

**Issue by bigsnarfdude** [snowplow/spark-streaming-example-project#11]
need to convert stolen sticker...

**Comment by alexanderdean** [comment]
Is this done?

**Comment by bigsnarfdude** [comment]
im gonna add the travis file but i dont know what needs to be done on the CI side of the house

**Comment by bigsnarfdude** [comment]
the current badge belongs and is point to https://github.com/snowplow/spark-example-project

**Comment by alexanderdean** [comment]
Fixed this.
