### ISSUE TITLE
Remove scripts folder

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/spark-streaming-example-project#15]
As all functions should be in tasks.py now

**Comment by bigsnarfdude** [comment]
i still need the scripts folder. data_load_kinesis.py is being used by invoke as its a generator for synthentic data

**Comment by alexanderdean** [comment]
Right - those functions should have been moved into invoke. A Python script calling another Python script via a Unix process is... messy.

**Comment by alexanderdean** [comment]
Done
