### ISSUE TITLE
Stream Data from Oracle to Cassandra using Spark Streeming

### ISSUE THREAD

**Issue by nirmalb06** [snowplow/spark-streaming-example-project#33]
Hi,

I have moved data from Oracle to Cassandra using spark, Now i want to Stream it to get those data as real time.

I just used a sample table in HR schema from oracle and moved the data to Cassandra table which has same structure. Now i want to Stream the date in real time to process the records and show it in reports. Please guide me in completing this live stream.

Thanks,
Nirmal.B

**Comment by alexanderdean** [comment]
Out of scope of a simple example project.
